name: flutter_application_1
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3         # Core Hive package
  hive_flutter: ^1.1.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  image_picker: 0.8.5+3
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  table_calendar: ^3.2.0
  flutter_dotenv: ^5.2.1
  http: ^1.4.0
  flutter_svg: ^2.1.0
  agora_rtc_engine: ^6.5.2
  permission_handler: ^12.0.0+1
  socket_io_client: ^2.0.0

  # flutter_plugin_android_lifecycle: ^2.0.6
dependency_overrides:
  flutter_plugin_android_lifecycle: 2.0.26


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - Assets/Group 6878.png
    - Assets/Rectangle 223.png
    - Assets/Vector.png
    - Assets/Checkbox/on.png
    - Assets/Group 36713(1).png
    - Assets/Rectangle 224.png
    - Assets/person.png
    - Assets/person2.png
    - Assets/person3.png
    - Assets/Frame 5.png
    - Assets/Frame 6.png
    - Assets/Group 36754.png
    - Assets/lucide_home.png
    - Assets/Group.png
    - Assets/lets-icons_setting-line.png
    - Assets/tabler_logout.png
    - Assets/fi-br-user.png
    - Assets/fi-br-shield-exclamation.png
    - Assets/fi-br-bell-ring.png
    - Assets/fi-br-lock.png
    - Assets/fi-br-calendar.png
    - Assets/Group(1).png
    - Assets/fi-br-shield-interrogation.png
    - Assets/fi-br-trash.png
    - Assets/fi-br-sign-out-alt.png
    - Assets/Frame 9.png
    - Assets/Group 120.png
    - Assets/fi-br-bell.png
    - Assets/Ellipse 38.png
    - Assets/Ellipse 39.png
    - Assets/Therapist_Welcome_image.png
    - Assets/Therapist_registeration_background.png
    - Assets/Therapist_registeration_background2.png
    - Assets/account-creation.png
    - Assets/image3.png
    - Assets/Therapist_Add_Photo.png
    - Assets/Google.png
    - Assets/Apple.png
    - Assets/Facebook.png
    - Assets/Therapist_Notification_image.png
    - Assets/Vector(2).png
    - Assets/home.png
    - Assets/list.png
    - Assets/plus.png
    - Assets/health.png
    - Assets/meditation.png
    - Assets/whoarewe.jpeg
    - Assets/user.png
    - Assets/Group 36731.png
    - Assets/emoticons 1.png
    - Assets/paper 1.png
    - Assets/yoga_384156 1.png
    - Assets/CHIBI1 2.png
    - Assets/fi-rr-cross.png
    - Assets/svg/
    - Assets/imgs/
    - Assets/logos/
    - Assets/Chat.png
    - Assets/Video.png
    - Assets/Profile.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
